

analyzer:
  plugins:
    - custom_lint
  exclude:
    - sample
    - test/**.dart

custom_lint:
  debug: true # enable debug mode
  verbose: true # enable verbose mode
  rules:
    - no_equal_then_else
    - prefer_returning_condition
    - avoid_print   
    - avoid_bang_operator: false 
    - prefer_void_callback
    - avoid_long_parameter_list:
      max-parameters: 5
      ignore-optional: true
      ignored-names: 'copyWith'
    - boolean_prefixes:
      ignore-getters: false
      ignore-fields: true
      ignore-parameters: false
      ignore-methods: true
      ignored-names: 'stringify'
      prefixes: 'is, are, was, were, has, have, had, can, will, do, does, did, should, with'
    - cyclomatic_complexity: false
      max_complexity: 10
    - max_nesting_level:
      number_of_level: 3
    - prefer_iterable_first
    - prefer_iterable_last
    - no_boolean_literal_compare
    - prefer_iterable_isempty
    - no_length_in_index_expression
    - unused_parameter:
      parameters: 'state, event'
    - equatable_props_check: false
    - add_cubit_suffix_rule
    - avoid_filter_usage
    - first_init_state
    - prefer_of_over_current
    - prefer_no_growable_list
    - prefer_underscore_for_unused_callback_parameters
    - remove_empty_listener
    - avoid_dynamic_return_type
    - copy_with_method_field_check
    - avoid_cached_network_image: false
    - avoid_nullable_list_return_type
    - verify_autoroute_usage: false
    - avoid_plus_usage
    - prefer_named_bool_parameters:
      ignore-single: false
      ignore-single-boolean: false
    - prefer_any_or_every
    - avoid_useless_spread
    - avoid_inverted_boolean_checks
    - avoid_map_keys_contains
    - avoid_long_records:
      max-number: 6
    - use_ternary_instead_of_if_else
    - avoid_extension_on_enum
    - avoid_nullable_boolean
    - avoid_local_function
    - avoid_equal_expressions
    - avoid_getter_prefix
    - avoid_self_assignment
    - avoid_single_child_column_or_row
