

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - number_of_parameters:
      max_parameters: 3
    - boolean_prefixes:
      prefixes: 'is, are, was, were, has, have, had, can, should, will, do, does, did'
