name: my_custom_lints_example
publish_to: none


environment:
  sdk: ">=3.0.0 <4.0.0"
  

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0


dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0  
  custom_lint: ^0.8.0
  

dependency_overrides:
  my_custom_lints:
    path: ../