name: my_custom_lints_example
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6


dev_dependencies:
  custom_lint: ^0.6.1
  my_custom_lints:
    path: ../
