name: my_custom_lints_example
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  my_custom_lints:
    path: ../
